workspaceId:
  development: K3s1DGYzFv1WxxK3
  production:
version: 0.0.0
ignoreParams:
  - alt
  - fields
  - userIp
  - quotaUser
  - prettyPrint
  - key
auth:
  name: Authorization
  in: header
  prefix: Bearer
