workspaceId:
  production: 5nSUXxACmPQWw66N
auth:
  name: Authorization
  in: header
  prefix: Bearer
  description: |
    Notion API key.
paramOverrides:
  - paramName: notionVersion
    overrides:
      advanced: true
      schema:
        type: 'string'
        default: 2022-06-28
