workspaceId:
  development: bCRYvfi8qAsgBZYr
  production: Y9Mmif5WBIbGp6FX
ignorePaths:
  - oauth
ignoreParams:
  - token
auth:
  name: Authorization
  in: header
  prefix: Bearer
  description: |
    Any supported Slack token (bot, workflow, user).
    Note: not all operations are supported with different token types.
